test: skip failing TestLatency in CI
the test is failing with the following error:
```
--- FAIL: TestLatency (0.00s)
    integration_test.go:65:
        	Error Trace:	/builds/jkito/bitmask-vpn/pkg/vpn/menshen/integration_test.go:65
        	Error:      	Received unexpected error:
        	            	socket: permission denied
        	Test:       	TestLatency
        	Messages:   	Could not calc latency
FAIL
FAIL	0xacab.org/leap/bitmask-vpn/pkg/vpn/menshen	0.029s
```

it is beacause of missing permissons, the pro-bing library attempts
to send an "unprivileged" ping via UDP. On Linux, this must be enabled
with a sysctl command