macos: fix a bug which crashed the app on start
this was happening because we use CGO along with
the C++ app, the go runtime creates an alternate
stack for signal handlers, but from C++ we  were
registering a signal handler on the threads main
stack, which caused a panic in the go runtime:

```
fatal error: non-Go code setup up signal handler without SA_ONSTACK flag
```

with this change we correctly assign the signal handler
the SA_ONSTACK flag

Signed-off-by: jkito <belter@riseup.net>